name: horda_core
description: Code shared by Horda's client and server packages.
version: 0.16.0
repository: https://github.com/horda-ai/dart_core

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.7.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
